export const stateProvideKey = Symbol("state")
export const propsProvideKey = Symbol("props")
export const selectionProvideKey = Symbol("selection")
export const optionsProvideKey = Symbol("options")
export const filterableProvideKey = Symbol("filterable")
